apiVersion: v1
kind: ConfigMap
metadata:
  name: php-fpm-conf
  namespace: ian
data:
  www.conf: |
    [www]
    user = 900
    group = 900
    listen = 9000
    listen.owner = 900
    listen.group = 900
    listen.mode = 0660
    pm = dynamic
    pm.max_children = 150
    pm.max_requests = 300
    pm.start_servers = 24
    pm.min_spare_servers = 24
    pm.max_spare_servers = 126
    pm.status_path = /status
    ping.path = /ping
    ping.response = OK
    catch_workers_output = yes
    request_terminate_timeout = 300
    clear_env = no

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: ian
data:
  nginx.conf: |
    server {
      listen 80;
      listen [::]:80;

      server_name _;
      root /var/www/service/;
      index index.php;

      location / {
        try_files $uri $uri/ /index.php$is_args$args;
      }      

      location ~ ^/(status|ping)$ {
        fastcgi_pass                  127.0.0.1:9000;
        fastcgi_index                 index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include                       fastcgi_params;
      }
    }
