apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm-demo
  namespace: ian
  labels:
    app: phpfpm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpfpm-demo
  template:
    metadata:
      labels:
        app: phpfpm-demo
    spec:
      containers:
        - name: php-fpm
          image: php:fpm
          workingDir: /var/www/service
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 100m
              memory: 1G
            limits:
              cpu: 100m
              memory: 1G
          volumeMounts:
            - name: application
              mountPath: /var/www/service/
            - name: php-fpm-config
              mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf

        - name: nginx
          image: nginx:alpine
          workingDir: /var/www/service
          ports:
            - containerPort: 80
          volumeMounts:
            - name: application
              mountPath: /var/www/service/
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/

        - name: phpfpm-exporter
          image: gcr.io/rd6-project/php-fpm_exporter:1.0
          env:
            - name: PHP_FPM_SCRAPE_URI
              value: "tcp://localhost:9000/status"
            - name: PHP_FPM_FIX_PROCESS_COUNT
              value: "true"
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 10m

        - name: prometheus-to-sd
          image: gcr.io/rd6-project/prometheus-to-sd:v0.9.0
          ports:
            - containerPort: 6060
              protocol: TCP
          command:
            - /monitor
            - --stackdriver-prefix=custom.googleapis.com
            - --monitored-resource-type-prefix=k8s_
            - --source=:http://localhost:9253
            - --pod-id=$(POD_NAME)
            - --namespace-id=$(POD_NAMESPACE)
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 10m
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: application
          emptyDir: {}
        - name: php-fpm-config
          configMap:
            name: php-fpm-conf
        - name: nginx-config
          configMap:
            name: nginx-conf
