apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: phpfpm-demo-hpa
  namespace: ian
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phpfpm-demo
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: phpfpm_active_processes
        target:
          averageValue: 50
          type: AverageValue
    - type: Pods
      pods:
        metric:
          name: phpfpm_idle_processes
        target:
          averageValue: 50
          type: AverageValue
    - type: Pods
      pods:
        metric:
          name: phpfpm_total_processes
        target:
          averageValue: 50
          type: AverageValue
    - type: Pods
      pods:
        metric:
          name: phpfpm_accepted_connections
        target:
          averageValue: 50
          type: AverageValue
